name: CI

on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest fastapi uvicorn jupyter
        
    - name: Run schema validation tests
      run: |
        pytest tests/test_schema.py -v
        
    - name: Validate API can start
      run: |
        timeout 10 python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 5
        curl -f http://localhost:8000/ || exit 1
        
    - name: Validate demo notebook
      run: |
        cd demo
        python -c "import json; json.load(open('data/synthetic_jobs.json')); print('✅ Demo data valid')"
        
    - name: Code quality check
      run: |
        # Basic code quality checks
        python -m py_compile app/main.py
        python -m py_compile app/services/*.py
        echo "✅ Code compiles successfully"
        
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for secrets
      run: |
        # Ensure no secrets leaked to repo
        ! grep -r "api_key\|secret\|password\|token" --include="*.py" --include="*.json" --include="*.md" . || exit 1
        echo "✅ No secrets found in repo"
        
    - name: Validate .gitignore
      run: |
        # Ensure sensitive files are ignored
        grep -q "\.env" .gitignore
        grep -q "secrets" .gitignore
        grep -q "config\.py" .gitignore
        echo "✅ Gitignore properly configured"